### ISSUE TITLE
[Administrative] Draft lounge locker policy

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#13]
### Task
To prevent people from locking their stuff in our lockers and not reclaiming them, we should develop a policy about locker usage. Some pointers to discuss:
- Recording details on who uses a locker (to track their usage, and to provide contact information in case we want to _bug_ them to reclaim their stuff)
- Maximum time limit for storage
- Actions we will take to get you to reclaim your stuff in time
- Actions we will take in case you don't reclaim your stuff
- What happens if you still don't claim your stuff after we remove them from our lockers and put them in safekeeping
- Banning people from the lounge due to locker misuse

### Steps
To complete this task:
- [ ] Discuss the above pointers in some executive meeting
- [ ] Draft the new policy
- [ ] Obtain executive approval and pass the review stage

**Comment by JasonBarahan** [comment]
I don't think they were ever free
