### ISSUE TITLE
[Finances] Obtain non-profit organization status

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#30]
### Task
Being a non-profit organization provides the following perks:
- no sales taxes (we are exempt)
- corporate freebies (free services, like Google Workspace - or discounted goods, like on TechSoup)
- can apply for NPO-specific grants/sources of funding

However there are reporting requirements and various other caveats when you have NPO status. Those reporting requirements are manageable though.

We can get NPO status to take advantage of the aforementioned perks and to help bring us more revenue.

### Steps
We are aiming for Ontario-sourced NPO status, registering within [Ontario's Business Registry ](https://www.ontario.ca/page/ontario-business-registry).
To complete this task:
- [ ] Get approval from the University, as our legal name will use the University's name
- [ ] Obtain an Ontario-biased Nuans name search for the CSSU
- [ ] Incorporate the CSSU. Will need to pay a filing fee and complete some forms.
- [ ] Complete tax filing forms
- [ ] Create an administrative document which has information on NPO reporting requirements, and what we will need to do

**Comment by JasonBarahan** [comment]
Closing this as this was a test suggestion
