### ISSUE TITLE
[Orientation] Invite Red Imposter as guest speaker

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#32]
### Task
We should invite Red Among Us imposter astrobro to be a motivational speaker for the lounge during orientation. If we book SRI we can really hype people up with his dance moves. Yellow imposter is not sus enough ![image](https://github.com/cssu/cssu.github.io/assets/122300705/4ce6be91-41c8-4381-918f-be1d9d37d901)

### Steps
- [ ] Get red imposter to speak for sus at orientation
- [ ] Make sure he isn't an imposter
- [ ] Make sure he won't vent hjhjhjhjhjhj

**Comment by JasonBarahan** [comment]
AMONG US!!!

(closing as shitpost)
