### ISSUE TITLE
[External] Sponsorships: Laurentian Bank

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#5]
### Task
https://www.laurentianbank.ca/en/about-us
Get a sponsorship from them. They're part of the Big 7 if I recall correctly.

Known for:
- Banking services

### Steps
 - [ ] Reach out to them and send our sponsorship package
 - [ ] Complete any meetings
 - [ ] Confirm their sponsorship tier
 - [ ] Have treasurer send invoice
 - [ ] Confirm payment

**Comment by JasonBarahan** [comment]
This was a test issue and will be closed.
